project:
  title: "apnielsen.com"
  output-dir: docs
  type: website

execute: 
  freeze: auto

copyright:
  holder: Aaron Nielsen
  year: 2025

website:
  # favicon: favicon.ico
  open-graph: true
  google-analytics: "G-XV3NXH8NG5"
  
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true

  repo-url: https://github.com/anielsen001/anielsen001.github.io
  repo-actions: [source,issue]
  
  navbar:
    title: "Aaron Nielsen's Personal Website"
    search: true

    right:
      - text: AFIT
        href: "https://www.afit.edu/BIOS/bio.cfm?facID=818"
      - text: "{{< ai orcid >}}"
        href: "https://orcid.org/0000-0003-1849-4611"
      - icon: github
        href: "https://github.com/anielsen001"
      - icon: linkedin
        href: "https://www.linkedin.com/in/aaronnielsen/"

  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Resume/CV"
        href: "http://apnielsen.com/cv/"

      - section: "Projects"
        contents:
          - text: "Bike radar reflectors"
            href: "https://www.apnielsen.com/bike-corner-relfector/"
          - text: "Dual-numbers and autodiff"
            href: "https://www.apnielsen.com/dual-numbers-auto-diff/"
          - text: "PyOdide interactive presentations"
            href: "https://whitenoisetech.codeberg.page/2025-03-12-ddl-pyodide/"
            
  page-footer: "Copyright 2025, Aaron Nielsen"
    
format: 
  html:
    theme: cosmo

  revealjs:
    height: 900
    width: 1600
    # logo: "mylogo.png"
    slide-number: true
    scrollable: false
    transition-speed: fast
    chalkboard: true
    link-external-newwindow: true
    theme: cosmo
    #css: my.css
